import type { Invoice } from "./home/InvoiceCard";

export const INVOICES: Invoice[] = [
  {
    id: "RT3080",
    createdAt: "2021-08-01",
    paymentDue: "2021-08-19",
    paymentTerms: "30",
    description: "Re-branding website design",
    clientName: "Jensen Huang",
    clientEmail: "jensen@techmail.com",
    status: "paid",
    senderAddress: {
      street: "19 Union Terrace",
      city: "London",
      postCode: "E1 3EZ",
      country: "United Kingdom",
    },
    clientAddress: {
      street: "Jensen Street 12",
      city: "San Francisco",
      postCode: "94105",
      country: "USA",
    },
    items: [
      { name: "Brand Guidelines", quantity: 1, price: 1800.9, total: 1800.9 },
    ],
    total: 1800.9,
  },
  {
    id: "XM9141",
    createdAt: "2021-09-01",
    paymentDue: "2021-09-20",
    paymentTerms: "30",
    description: "Landing page redesign",
    clientName: "Alex Grim",
    clientEmail: "alex@grimmail.com",
    status: "pending",
    senderAddress: {
      street: "19 Union Terrace",
      city: "London",
      postCode: "E1 3EZ",
      country: "United Kingdom",
    },
    clientAddress: {
      street: "Grim Avenue 88",
      city: "New York",
      postCode: "10001",
      country: "USA",
    },
    items: [{ name: "UI Design", quantity: 2, price: 278, total: 556.0 }],
    total: 556.0,
  },
  {
    id: "RG0314",
    createdAt: "2021-09-10",
    paymentDue: "2021-10-01",
    paymentTerms: "30",
    description: "Website development project",
    clientName: "John Morrison",
    clientEmail: "john@morrison.com",
    status: "paid",
    senderAddress: {
      street: "19 Union Terrace",
      city: "London",
      postCode: "E1 3EZ",
      country: "United Kingdom",
    },
    clientAddress: {
      street: "Morrison Road 44",
      city: "Toronto",
      postCode: "M5H 2N2",
      country: "Canada",
    },
    items: [
      { name: "Frontend Development", quantity: 1, price: 9000, total: 9000 },
      {
        name: "Backend Integration",
        quantity: 1,
        price: 5002.33,
        total: 5002.33,
      },
    ],
    total: 14002.33,
  },
  {
    id: "RT2080",
    createdAt: "2021-09-25",
    paymentDue: "2021-10-12",
    paymentTerms: "14",
    description: "Logo design update",
    clientName: "Alysa Werner",
    clientEmail: "alysa@werner.com",
    status: "pending",
    senderAddress: {
      street: "19 Union Terrace",
      city: "London",
      postCode: "E1 3EZ",
      country: "United Kingdom",
    },
    clientAddress: {
      street: "Werner Street 9",
      city: "Berlin",
      postCode: "10115",
      country: "Germany",
    },
    items: [{ name: "Logo Concept", quantity: 2, price: 51.02, total: 102.04 }],
    total: 102.04,
  },
  {
    id: "AA1449",
    createdAt: "2021-10-01",
    paymentDue: "2021-10-14",
    paymentTerms: "14",
    description: "App design and prototype",
    clientName: "Mellisa Clarke",
    clientEmail: "mellisa@clarke.com",
    status: "pending",
    senderAddress: {
      street: "19 Union Terrace",
      city: "London",
      postCode: "E1 3EZ",
      country: "United Kingdom",
    },
    clientAddress: {
      street: "Clarke Road 77",
      city: "Sydney",
      postCode: "2000",
      country: "Australia",
    },
    items: [
      { name: "Wireframes", quantity: 2, price: 1500, total: 3000 },
      { name: "Prototype", quantity: 1, price: 1032.33, total: 1032.33 },
    ],
    total: 4032.33,
  },
  {
    id: "TY9141",
    createdAt: "2021-10-15",
    paymentDue: "2021-10-31",
    paymentTerms: "14",
    description: "Marketing website build",
    clientName: "Thomas Wayne",
    clientEmail: "thomas@wayne.com",
    status: "pending",
    senderAddress: {
      street: "19 Union Terrace",
      city: "London",
      postCode: "E1 3EZ",
      country: "United Kingdom",
    },
    clientAddress: {
      street: "Wayne Manor",
      city: "Gotham",
      postCode: "00001",
      country: "USA",
    },
    items: [
      { name: "Landing Page", quantity: 1, price: 6155.91, total: 6155.91 },
    ],
    total: 6155.91,
  },
  {
    id: "FV2353",
    createdAt: "2021-11-01",
    paymentDue: "2021-11-12",
    paymentTerms: "14",
    description: "Internal dashboard system",
    clientName: "Anita Wainwright",
    clientEmail: "anita@wainwright.com",
    status: "draft",
    senderAddress: {
      street: "19 Union Terrace",
      city: "London",
      postCode: "E1 3EZ",
      country: "United Kingdom",
    },
    clientAddress: {
      street: "Wainwright Blvd 3",
      city: "Dublin",
      postCode: "D02",
      country: "Ireland",
    },
    items: [
      { name: "Dashboard UI", quantity: 1, price: 3102.04, total: 3102.04 },
    ],
    total: 3102.04,
  },
];
